[[redirects]]
  from = "/gameserverapi/battlepass/active"
  to = "/.netlify/functions/battlepass"
  status = 200
  force = true

[[redirects]]
  from = "/grants"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/mcrt-price"
  to = "/.netlify/functions/mcrt-price"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_ZEUS_DROP_UTC = "2025-09-05T12:00:00Z"


  GAMESERVER_API_PORT = "8913"
  GAMESERVER_API_KEY = "45AXiLa77sqkcfT0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://widgets.coingecko.com https://translate.google.com https://translate.googleapis.com https://static.cloudflareinsights.com https://*.xswap.link https://*.xswap.dev https://*.1inch.io https://*.metamask.io https://*.walletconnect.org https://www.youtube.com https://*.youtube.com https://www.gstatic.com https://www.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://www.gstatic.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https: https://img.youtube.com https://i.ytimg.com https://*.ytimg.com https://*.githubusercontent.com; media-src 'self' https://res.cloudinary.com; connect-src 'self' https: http: wss: https://*.xswap.link https://*.xswap.dev https://*.binance.org https://*.ethereum.org https://*.polygon.technology https://*.1inch.io https://*.coingecko.com https://*.coinmarketcap.com https://www.youtube.com https://*.youtube.com https://www.googleapis.com https://translate.googleapis.com https://nitter.net https://nitter.pufe.org https://nitter.poast.org https://nitter.hu https://n.opnxng.com https://nitter.holo.host http://5.9.111.150:* http://51.79.230.134:* http://51.222.44.25:*; frame-src 'self' https://widgets.coingecko.com https://www.youtube.com https://youtube.com https://www.youtube-nocookie.com https://*.youtube.com https://*.youtube-nocookie.com https://*.xswap.link https://*.xswap.dev https://*.walletconnect.org https://*.metamask.io https://twitframe.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"